// svelte/src/components/ListControl.svelte
<script>
    export var items;
    let itemToAdd = "";
    let i = 0;

    $: selected = items[i];

    const addItem = () => {
        if (itemToAdd === "")
            return;

        items = items.concat(itemToAdd);
        i = items.length - 1;
    };

    const removeItem = () => {
        const index = items.indexOf(selected);
        items = [...items.slice(0, index), ...items.slice(index+1)];

        i = Math.min(i, items.length - 2)
    }
</script>

<div class="container">
    <div class="controls">
        <input type="text" bind:value={itemToAdd}>
        <button on:click={addItem} >Add</button>
        <button on:click={removeItem}>Remove</button>
    </div>

    <div class="list">
        <select bind:value={i} size={5}>
            {#each items as item, i}
                <option value={i}>{item}</option>
            {/each}
        </select>
    </div>
</div>

<style>
    div {
        padding: 4px;
    }

    div.container {
        width: 30%;
        background-color: lightgray;
    }
    
    div.list select {
        width: 100%;
    }
</style>

// react-app/src/components/ListControl.js
import {useState} from 'react';
import "./ListControl.css";

export default function ListControl({startingItems}) {
    let [items, setItems] = useState(startingItems);
    const [newItem, setNewItem] = useState("");
    const [i, setI] = useState(0);
    const [selected, setSelected] = useState(items[i]);

    const addItem = () => {
        if (newItem === "")
            return;

        setItems(items.concat(newItem));
        setI(items.length - 1);
    };

    const removeItem = () => {
        const index = items.indexOf(selected);
        setItems([...items.slice(0, index), ...items.slice(index+1)]);

        setI(Math.min(i, items.length - 2));
    }

    const listItems = items.map((item, index) => <option value={item} key={index}>{item}</option>);
    return (
        <div className='container'>
            <div className='controls'>
                <input type="text" onChange={(e) => setNewItem(e.target.value)}></input>
                <button onClick={addItem}>Add</button>
                <button onClick={removeItem}>Remove</button>
            </div>

            <div className='list'>
                <select onChange={(e) => setSelected(e.target.value)} size={5}>
                    {listItems}
                </select>
            </div>
        </div>
    );
}
